name: go test

on: [push, pull_request]

premissions: 
  # TODO
  # Note that since we're automatically formatting ill formatted code
  # on any push as well as pull requests. It might be dangerous to
  # setup write permission on PRs, but maybe not since the write
  # is probably going to happen on the branch where the PR takes
  # is originating from, maybe. Need to make sure.
  contents: write

defaults:
  run:
    shell: bash

jobs:
  fmt test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.21
    steps:
      -name: go fmt
      -uses: actions/checkout@v4
      run: | 
        # Run go fmt in each directory
        for i in $(find . -not -path '*/.*' -type d)
        do 
          cd $i 
          go fmt 
          cd - 
        done
        # commit changes if any
        git add -u
        if [[ $(git diff HEAD --name-only | wc -l | bc) > 0 ]]; then
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m 'bot: gofmt'
          git push
        fi
      -name: go test
      run: | 
        # Run go fmt in each directory
        for i in $(find . -not -path '*/.*' -type d)
        do 
          cd $i 
          go test 
          cd - 
        done
